### ISSUE TITLE
Lỗi khi thêm lệnh cargo

### ISSUE THREAD

**Issue by ptkhai15** [openedu101/Rust-bootcamp-2024#2]
Em gặp phải lỗi này khi thực hiện thêm lệnh cargo thì có cách xử lý không ạ ?
![Screenshot 2023-12-05 093347](https://github.com/openedu101/Rust-bootcamp-2024/assets/94296191/07891943-57c4-4295-bba9-15194b586bf7)

**Comment by CocDap** [comment]
Cái này bạn dùng Linux thì cách source khác nhé. Cái đó `source` của MacOS
